name: test
run-name: ${{ github.actor }} is running tests.
on: [push]
jobs:
  run-typescript-check:
    name: Run a typescript check on all js and ts files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npx tsc --noEmit
  run-unit-tests:
    name: Run the unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm test
  run-functional-tests:
    name: Run the functional tests headless
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - name: Cypress
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          start: npm run dev:functional
          wait-on: 'http://localhost:8080'
